// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChannelType string

const (
	ChannelTypeTEXT  ChannelType = "TEXT"
	ChannelTypeVOICE ChannelType = "VOICE"
)

func (e *ChannelType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChannelType(s)
	case string:
		*e = ChannelType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChannelType: %T", src)
	}
	return nil
}

type NullChannelType struct {
	ChannelType ChannelType
	Valid       bool // Valid is true if ChannelType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannelType) Scan(value interface{}) error {
	if value == nil {
		ns.ChannelType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChannelType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannelType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChannelType), nil
}

type FriendshipStatus string

const (
	FriendshipStatusPENDING  FriendshipStatus = "PENDING"
	FriendshipStatusACCEPTED FriendshipStatus = "ACCEPTED"
	FriendshipStatusBLOCKED  FriendshipStatus = "BLOCKED"
)

func (e *FriendshipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendshipStatus(s)
	case string:
		*e = FriendshipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendshipStatus: %T", src)
	}
	return nil
}

type NullFriendshipStatus struct {
	FriendshipStatus FriendshipStatus
	Valid            bool // Valid is true if FriendshipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendshipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FriendshipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendshipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendshipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendshipStatus), nil
}

type MentionType string

const (
	MentionTypeUSER MentionType = "USER"
	MentionTypeROLE MentionType = "ROLE"
)

func (e *MentionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MentionType(s)
	case string:
		*e = MentionType(s)
	default:
		return fmt.Errorf("unsupported scan type for MentionType: %T", src)
	}
	return nil
}

type NullMentionType struct {
	MentionType MentionType
	Valid       bool // Valid is true if MentionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMentionType) Scan(value interface{}) error {
	if value == nil {
		ns.MentionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MentionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMentionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MentionType), nil
}

type SubmissionStatus string

const (
	SubmissionStatusASSIGNED SubmissionStatus = "ASSIGNED"
	SubmissionStatusTURNEDIN SubmissionStatus = "TURNED_IN"
	SubmissionStatusLATE     SubmissionStatus = "LATE"
	SubmissionStatusRETURNED SubmissionStatus = "RETURNED"
)

func (e *SubmissionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionStatus(s)
	case string:
		*e = SubmissionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionStatus: %T", src)
	}
	return nil
}

type NullSubmissionStatus struct {
	SubmissionStatus SubmissionStatus
	Valid            bool // Valid is true if SubmissionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionStatus), nil
}

type UserStatus string

const (
	UserStatusONLINE  UserStatus = "ONLINE"
	UserStatusIDLE    UserStatus = "IDLE"
	UserStatusDND     UserStatus = "DND"
	UserStatusOFFLINE UserStatus = "OFFLINE"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Assignment struct {
	ID             pgtype.UUID
	WorkspaceID    pgtype.UUID
	ChannelID      pgtype.UUID
	CreatorID      pgtype.UUID
	Title          string
	Instructions   pgtype.Text
	PointsPossible pgtype.Int2
	DueDate        pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AssignmentSubmission struct {
	ID           pgtype.UUID
	AssignmentID pgtype.UUID
	StudentID    pgtype.UUID
	Status       SubmissionStatus
	SubmittedAt  pgtype.Timestamptz
	Attachments  []byte
	Grade        pgtype.Int2
	Feedback     pgtype.Text
}

type AuditLog struct {
	ID          int64
	WorkspaceID pgtype.UUID
	ActorID     pgtype.UUID
	ActionType  string
	TargetType  pgtype.Text
	TargetID    pgtype.Text
	Changes     []byte
	CreatedAt   pgtype.Timestamptz
}

type Channel struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Name        string
	Type        ChannelType
	Topic       pgtype.Text
	Position    pgtype.Int4
	CreatedAt   pgtype.Timestamptz
}

type Conversation struct {
	ID      pgtype.UUID
	IsGroup bool
	Name    pgtype.Text
}

type ConversationParticipant struct {
	UserID         pgtype.UUID
	ConversationID pgtype.UUID
}

type DirectMessage struct {
	ID             int64
	ConversationID pgtype.UUID
	AuthorID       pgtype.UUID
	Content        pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

type Friendship struct {
	UserOneID    pgtype.UUID
	UserTwoID    pgtype.UUID
	Status       FriendshipStatus
	ActionUserID pgtype.UUID
}

type Invite struct {
	ID          pgtype.UUID
	Code        string
	WorkspaceID pgtype.UUID
	CreatorID   pgtype.UUID
	MaxUses     pgtype.Int4
	CurrentUses pgtype.Int4
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Member struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	WorkspaceID          pgtype.UUID
	RoleID               pgtype.UUID
	Nickname             pgtype.Text
	NotificationSettings []byte
	JoinedAt             pgtype.Timestamptz
}

type Mention struct {
	MessageID       int64
	MentionedUserID pgtype.UUID
	MentionType     MentionType
}

type Message struct {
	ID           int64
	ChannelID    pgtype.UUID
	AuthorID     pgtype.UUID
	Content      pgtype.Text
	ParentID     pgtype.Int8
	Attachments  []byte
	Reactions    []byte
	IsScheduled  pgtype.Bool
	ScheduledFor pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type MessageReadStatus struct {
	MessageID int64
	UserID    pgtype.UUID
	ReadAt    pgtype.Timestamptz
}

type PinnedMessage struct {
	MessageID      int64
	ChannelID      pgtype.UUID
	PinnedByUserID pgtype.UUID
	PinnedAt       pgtype.Timestamptz
}

type Poll struct {
	ID        pgtype.UUID
	MessageID int64
}

type PollOption struct {
	ID         pgtype.UUID
	PollID     pgtype.UUID
	OptionText string
}

type PollVote struct {
	OptionID pgtype.UUID
	UserID   pgtype.UUID
}

type Recording struct {
	ID               pgtype.UUID
	ChannelID        pgtype.UUID
	ScheduledEventID pgtype.UUID
	StartedByID      pgtype.UUID
	FileUrl          string
	FileSizeBytes    pgtype.Int8
	DurationSeconds  pgtype.Int4
	CreatedAt        pgtype.Timestamptz
}

type Role struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Name        string
	Permissions int64
}

type ScheduledEvent struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	ChannelID   pgtype.UUID
	CreatorID   pgtype.UUID
	Title       string
	Description pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
}

type Task struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Content     string
	IsCompleted bool
	DueDate     pgtype.Date
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	PasswordHash pgtype.Text
	AvatarUrl    pgtype.Text
	AboutMe      pgtype.Text
	SocialLinks  []byte
	Status       NullUserStatus
	CustomStatus pgtype.Text
	Provider     string
	ProviderID   pgtype.Text
	Settings     []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Webhook struct {
	ID        pgtype.UUID
	ChannelID pgtype.UUID
	Name      string
	TokenHash string
	AvatarUrl pgtype.Text
}

type Workspace struct {
	ID                     pgtype.UUID
	Name                   string
	OwnerID                pgtype.UUID
	IconUrl                pgtype.Text
	IsPublic               pgtype.Bool
	Description            pgtype.Text
	Tags                   []string
	WelcomeChannelID       pgtype.UUID
	WelcomeMessageTemplate pgtype.Text
	CreatedAt              pgtype.Timestamptz
}
