// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :one
INSERT INTO members (
  user_id,
  workspace_id
) VALUES (
  $1, $2
)
RETURNING id, user_id, workspace_id, role_id, nickname, notification_settings, joined_at
`

type AddWorkspaceMemberParams struct {
	UserID      pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, addWorkspaceMember, arg.UserID, arg.WorkspaceID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.RoleID,
		&i.Nickname,
		&i.NotificationSettings,
		&i.JoinedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  email,
  password_hash
) VALUES (
  $1, $2, $3
)
RETURNING id, username, email, password_hash, avatar_url, about_me, social_links, status, custom_status, provider, provider_id, settings, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.AboutMe,
		&i.SocialLinks,
		&i.Status,
		&i.CustomStatus,
		&i.Provider,
		&i.ProviderID,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
  name,
  owner_id
) VALUES (
  $1, $2
)
RETURNING id, name, owner_id, icon_url, is_public, description, tags, welcome_channel_id, welcome_message_template, created_at
`

type CreateWorkspaceParams struct {
	Name    string
	OwnerID pgtype.UUID
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.IconUrl,
		&i.IsPublic,
		&i.Description,
		&i.Tags,
		&i.WelcomeChannelID,
		&i.WelcomeMessageTemplate,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, avatar_url, about_me, social_links, status, custom_status, provider, provider_id, settings, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.AboutMe,
		&i.SocialLinks,
		&i.Status,
		&i.CustomStatus,
		&i.Provider,
		&i.ProviderID,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, avatar_url, about_me, created_at FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	AvatarUrl pgtype.Text
	AboutMe   pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.AboutMe,
		&i.CreatedAt,
	)
	return i, err
}

const isWorkspaceMember = `-- name: IsWorkspaceMember :one
SELECT EXISTS(
  SELECT 1 FROM members WHERE user_id = $1 AND workspace_id = $2
)
`

type IsWorkspaceMemberParams struct {
	UserID      pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) IsWorkspaceMember(ctx context.Context, arg IsWorkspaceMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceMember, arg.UserID, arg.WorkspaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUserWorkspaces = `-- name: ListUserWorkspaces :many
SELECT w.id, w.name, w.owner_id, w.icon_url, w.is_public, w.description, w.tags, w.welcome_channel_id, w.welcome_message_template, w.created_at FROM workspaces w
JOIN members m ON w.id = m.workspace_id
WHERE m.user_id = $1
`

func (q *Queries) ListUserWorkspaces(ctx context.Context, userID pgtype.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listUserWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.IconUrl,
			&i.IsPublic,
			&i.Description,
			&i.Tags,
			&i.WelcomeChannelID,
			&i.WelcomeMessageTemplate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
